services:
  torbox:
    image: mrjoiny/torbox-auto-downloader:${IMAGE_TAG:-latest}
    volumes:
      - ${HOST_WATCH_PATH}:${CONTAINER_WATCH_DIR}
      - ${HOST_DOWNLOAD_PATH}:${CONTAINER_DOWNLOAD_DIR}
    env_file:
      - .env
    environment:
      WATCH_DIR: ${CONTAINER_WATCH_DIR}
      DOWNLOAD_DIR: ${CONTAINER_DOWNLOAD_DIR}
    restart: unless-stopped
